language: ruby
dist: bionic
rvm:
  - 2.7.1
cache:
  bundler: true
notifications:
  slack:
    secure: 5pZFML5yIC7ri3DyQFXQyVbb2kmwIG/Z5Myeb/9KuYPZC6jRGdfvktq0OvhdDCb3+w0mcnkoXWYKNqKdUrTMamKd9Du6dUiig2/4XK01710+m7Qm8tKuMneDTa3utxMSxMpzlZsJAHcBpZTOhr6vD1FovGZu4dCOjJAP8buM7ZzPzSVZDj4gSWXjSDTovMmJfdY2/f82sXn+lfXCGXlCo77notxqXERtsF5gPBB4mw1dVwtYOl4C7XbrvO32RUKuhW6kkPloIC7dk6mLebU/uVUqTXP3WPJfFQF7SqyBejrvVvFRC8k7NoS51HPCjJ+kG8+6Svw5w3Tatz9/sMFktICsb3toO8NCNh9dvjmCM3BT1WTg02T2Zfn3ZOQC5EcpsNns2CMnwSScXrldrY64GyA/FE1tPdbOfhFiCAk3Sk3a1VV6G/MF0dOhoDQt97LcmJz9ktmHbbyML/0/fxtLBBrjGe/cznBWMZAXv4Imm8GNRqQmS52aeSndq2AViEsp3Wl5ZEIJ016QCq8h7uX4fTJyj2QnD+Nfv958EBl3DwT+fjJUr4+rDCgdBOvYkD47LCJP8YswPfsigJVfzayW0Qf4+3D1U4H9LSkSYb/gQYVcA4Nd2VMw0aJpz8esDVR/GPBpKZ6YFXGczAcjTriH5hQmGRLz86wKWAB8Gg2VTKs=
