language: ruby
dist: bionic
rvm:
- 2.7.1
cache:
  bundler: true
notifications:
  slack:
    rooms:
      secure: bOsr4IHlD9vcFppESzh/g6u2pvK17HznkDlRzmlN9+DXxomt1AtekpQPbIlCZK5jEWIhW8UWdxsIT0hzL0Eq8uu36WS3IP5kx977aM3wRCClxRH5Bwt4rMPHBnl3NChOlsWq1oypisOTI3kbXfcblJWb3Tv4IzEV0lOQQJ6QjWd5GR4SfBAGBxbhcXs+7HnlffuweJ83jJMOFHQxRfzP+/z+GahwMKJi8mbOH3r8LzSUdoLPxybJrlBH62w3/udB7T7xXhxxWhQBiCs+fDVl2YCpYhpp8v3Zf17JEct73G8MGMvmHZ2H+r4CMjTY5pKSxsxnAWHZjPWu/w0B+kuGKDsWe/mblFgIa/iZ5MrCxze5Ec0VkXHgh0GQGB0Dtm8kf/KbdTNcfcoQ1a7kxyPyAF/wUQzhiAo6I8F1jbxiIWH4xPMJpH+hCeYEkfr7y+8jjXWBfFsEAIafvLCAzybSHm+56P4zgrB+hk98tdOCbf9bmSCq7cnBQjybtc9qNrdPK8cfb8VbosjvXF7wuUMd8CVRPXBk8bn7g5cbfX4+ABXu2UrSI/J9QwWww5RRoBtX37emI6S8E7rRQciA5t/EkvrwdmpsmV7ZeO2RZ9/5zwfoO04lteC8qHNFkexCMMukJPH2T1kmEdZ0fqIBuz8qcGcGHSPmQS6Rvw5pzXIxVYo=
