language: ruby
dist: bionic
rvm:
- 2.7.1
cache:
  bundler: true
notifications:
  slack:
    secure: NL7etEN/fc/c/dixEa9DYCHfq1Y8BkTLPWOM4zUEu2JtBd0Lp1Hey0SboUnMXwLIK1yng9/oad9tWoTN1ikqspGZDKw/48YVL+dS/7pSszt8pK4iUFDaNTE31BMGerTMJPBW9mPDwNajIF7eeNDVR5rTfhgD2GhapUXkrohe3bbiMuqeDCq+v6tADRPBC9IqAsBIRoT4DgeKYGcWXU0Z6eHnhx42I26YqB5ovvxD2AzGyskp1DWWh24toufjVhPVL+laBQhI1gtB6ZDLB8ynkD6EFbSVgkrVi1Iq8rKhDmy6KwVeC19PxFZf42czWsBw5HRas5/Xp5yrGf0gKhIcj+bb2wuEY6In12AqX5x2sg1jNMrH19/iXoX7Q9c4h28GI67k1pBwv8N2dD4LWnFjSzCT2BuQEitq8VNuUfglVRV/u+Iv1BxnMqt/nGhn4v5iQdtsMpMJ97A0/8w3f22uZhVlQ6e32BYGDuH2Zc5Lm+Wr0fObgTifOYBf1yKerVuyGUE+grkC0ESyXtZUaeVl8CvRkB+X4SPAP68pN1k4ma/8EsEXmK3s6KFB4K8cNlddqmpsOiOlAVLGVA/dR+sMI3IoF24kHTlzJb53LO28+7VlOcWdWXTwtduGwr6ss7fxNOxa/j3UKW0U8BUS/tpCMHchit9s+kogndTvtxc9fLI=
