language: ruby
dist: bionic
rvm:
- 2.6.2
- 2.7
cache:
  bundler: true
notifications:
  slack:
    secure: u/8B1oyLGVu5Ymxl60YfoJDAiqF+ZumKMM+0oMrwuPc3d1xxHNutNGSRVJ2mj6CvVQWFkrAWwFOwpOtq+YxAOR35V32kpso0DcFYhs/3RAK7st5I6dBlXLT0nsh102yRKN7mdAYHolFMSF6szdXJrvEt6aWgWnT5ITHt66ZB6Lt3QRBdybod0MzEdtmYoe12gUBzZqbzA/MIMmy4j49GIazPsiOj7W8g/YV/XW5aozJuu3v6Cp7SRlVclzEDEQQx2oKdXjVArHv9Wc7GVkTrWss5vr8/jny2VQPV+m1gOpn2Ie8x7hlqYEMiz3z1ONQevrs6CgQLJSZ7zj8+73Vye4evxm4MXGrXRZKo4wdXLTJBsOZUWWDpkoJLLNli7uEy03m3ddQW88LkOlG7aRnaoJYIirQmdZ3F5U5+9kyyfbDpUKQswSgxhWH55AHg2jUJhg7fu5aSCUZ10Y6FYXZXdgV1lu4+gWwvo5Hvea54KbjMkzOR4MRiEhz3qZa2r5rsRhyoA3k+kQ+czbUO4gnYmLsK/s6btByI3aICKQgMFzOg5ALM0kytLk/ND7G3uCicco/sWHcV1r5CfEcZgcY+vJnHoz6n96eqLqJfq1ZwDWfsn7DXOUWKuFzOzzdc/EO28yKs31+kZROeP7E3XKm58l7Me1yOkVdr+QeC4mzqhP4=
env:
  global:
  - secure: m/N6qk/17Eo/iIqa6ASpwTqObDKqnj6TowHQRmOyrp3abueC6iOJXqhEiRevbDyKm6c7ku2HjtYTUgcE8GckYjRwjmhYbiQHsjtkmMCde5IzD7raOlcsQqZ9LSXtDE5JDEGumT9xD/30LzGxlhi+KHpJvCATIGFYyapOClGa+b9aH1tv7dEVGqzinmiSyU3/YUSmQsulzG4gKr8QI64Jr1Sz+rS36DxiOBWDBxVXb5HhVxcWY635+G6VcXf7S/Kp5XOhHwuc3ypy1xCQ1dhV0SR8i+QlKS0YRWndUFqCSZFWB30WMjZTkPlIrW8EpLl0sosHvUzGEdisRHn0OAWtDOSvfmob3UbrZlAJqG+yd4Kjz0SI72zG7UQvjhrFXahrNJ86wLEtAj3RF65WYTPG34O1XKCAp4l1TspA+OPNzyWV5Gx8XuixLVFaE/IZUK186uBlOAjeI6QoWzGaLzgEk58AmKJZanAM+pc4eN/mSZuBReXl61Poffqr5LORgjCcKBetEN/xQBkd3f4F/im4GNO/m6JX6MKwrd1HhbrvKWuv4NDDoFJCNYDVeTAak7l9y6joF0bJfjqcOaVQI6Xl1Lt7sVYNMA5Dxvo+Sjy1u+JkBVYedl/jNbwCOmEBAWyQbszy9Tm+TkJK5+bsZL4oFo2kuUHCBxBGGFO1vMC1K20=
before_install:
- gem install bundler
- bundle --version
before_script:
- echo -e "build ruby version $TRAVIS_RUBY_VERSION"
- if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
- if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi
script: bundle exec rspec
after_script:
- if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
  fi
