language: ruby
dist: bionic
rvm:
  - 2.6.2
  - 2.7
cache:
  bundler: true
notifications:
  slack:
    rooms:
      secure: u/8B1oyLGVu5Ymxl60YfoJDAiqF+ZumKMM+0oMrwuPc3d1xxHNutNGSRVJ2mj6CvVQWFkrAWwFOwpOtq+YxAOR35V32kpso0DcFYhs/3RAK7st5I6dBlXLT0nsh102yRKN7mdAYHolFMSF6szdXJrvEt6aWgWnT5ITHt66ZB6Lt3QRBdybod0MzEdtmYoe12gUBzZqbzA/MIMmy4j49GIazPsiOj7W8g/YV/XW5aozJuu3v6Cp7SRlVclzEDEQQx2oKdXjVArHv9Wc7GVkTrWss5vr8/jny2VQPV+m1gOpn2Ie8x7hlqYEMiz3z1ONQevrs6CgQLJSZ7zj8+73Vye4evxm4MXGrXRZKo4wdXLTJBsOZUWWDpkoJLLNli7uEy03m3ddQW88LkOlG7aRnaoJYIirQmdZ3F5U5+9kyyfbDpUKQswSgxhWH55AHg2jUJhg7fu5aSCUZ10Y6FYXZXdgV1lu4+gWwvo5Hvea54KbjMkzOR4MRiEhz3qZa2r5rsRhyoA3k+kQ+czbUO4gnYmLsK/s6btByI3aICKQgMFzOg5ALM0kytLk/ND7G3uCicco/sWHcV1r5CfEcZgcY+vJnHoz6n96eqLqJfq1ZwDWfsn7DXOUWKuFzOzzdc/EO28yKs31+kZROeP7E3XKm58l7Me1yOkVdr+QeC4mzqhP4=
addons:
  code_climate:
    repo_token:
      secure: "fTt76JqkkPPoHUGr8RWX8QcPw4Ju/CNw2EmHWRZkv2T7DU94Scb2dQxykcLRo1bTrhk6dd28eUdBPKz8VvXEMFnaFPpMv9JQcazAL9jc5MFK96Df11VvU+ZhcvM8ITimECCnNBs3lzZQPT9L9juZAfJrpq6x5dEXQK+WcJ9mDPT9QL+edktsUFb++7VoB5+AiMDRCi/BzRAmmRQzD3w/FLOwa6Y0wwus9yGp2J5yM3RXb4wWzhRbtoRodxpVY8CmOh9GFshI3TW5/g0+JwGP9KO4oqMd1lKAK7m0waIlMoDF4SOULjaE0pS35Pa11d5UPtHazmW3p7Q/9cI6DtdlkzacUyIOavhcHmkLaHCgSuY83V9bz/ZQHEujJkQiC6Nn/JvK3TzA8dpKJN6vasLYWuNuATCkRmcgY6kSSGM2gEzQiKcEMwQdFeU+MoDp1o9O3Z/YleCtTCL8CDjSrjqaOUGnCoXCs8Vim3Pv2b43+Xu28PO5y8SOG9VFd8edI0hkFnQQRBCAkaKmVgR/cwVvF9cxiEDjuAgF9keTaUSZxD+GTv7vOGMBJCQdK0P24GLBvB+SAgNsQpTHFa/x+CRfpQWCigUiTeuFy+eWZiTZq4DJ7o8KMGjEDsxlYGSeU+zUsjkQgQwunZg2th2HtKNPRYtsfzXxS7tHZY2xMR7OWlw="

before_install:
  - gem install bundler
  - bundle --version

before_script:
  - echo -e "build ruby version $TRAVIS_RUBY_VERSION"
  # Only run code coverage reporting in MRI/YARV
  - if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi

script: bundle exec rspec

after_script:
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
