language: ruby
dist: bionic
rvm:
- 2.6.2
- 2.7
cache:
  bundler: true
notifications:
  slack:
    secure: u/8B1oyLGVu5Ymxl60YfoJDAiqF+ZumKMM+0oMrwuPc3d1xxHNutNGSRVJ2mj6CvVQWFkrAWwFOwpOtq+YxAOR35V32kpso0DcFYhs/3RAK7st5I6dBlXLT0nsh102yRKN7mdAYHolFMSF6szdXJrvEt6aWgWnT5ITHt66ZB6Lt3QRBdybod0MzEdtmYoe12gUBzZqbzA/MIMmy4j49GIazPsiOj7W8g/YV/XW5aozJuu3v6Cp7SRlVclzEDEQQx2oKdXjVArHv9Wc7GVkTrWss5vr8/jny2VQPV+m1gOpn2Ie8x7hlqYEMiz3z1ONQevrs6CgQLJSZ7zj8+73Vye4evxm4MXGrXRZKo4wdXLTJBsOZUWWDpkoJLLNli7uEy03m3ddQW88LkOlG7aRnaoJYIirQmdZ3F5U5+9kyyfbDpUKQswSgxhWH55AHg2jUJhg7fu5aSCUZ10Y6FYXZXdgV1lu4+gWwvo5Hvea54KbjMkzOR4MRiEhz3qZa2r5rsRhyoA3k+kQ+czbUO4gnYmLsK/s6btByI3aICKQgMFzOg5ALM0kytLk/ND7G3uCicco/sWHcV1r5CfEcZgcY+vJnHoz6n96eqLqJfq1ZwDWfsn7DXOUWKuFzOzzdc/EO28yKs31+kZROeP7E3XKm58l7Me1yOkVdr+QeC4mzqhP4=
env:
  global:
    - secure: cUxeBjmrj1xe02G+XyGHnJXz8tH0kpI4T+8WSFNO4IoSSQgvtXEaqVSbqEtLOkvSkocrfxN4LLZxA64EqFY5pdVUxF5SYAdmdFvR/LHuSJ7JygMVuhl9BAXVopOwtBQHCiWaQzYuwZGzKXPmYmlmbdHg3euD2NEQbokNlak8rCrbF5W8N/HnPVGR2Z8TY991eKRLJpCQ/QyIXNiRDZWp8t/DGtCVeVoyZDRewiBYEE+ljv4AJR5mnHoqLhPbnx4MSP0Vw+BoO0eQHFbaTcnq2/SpTo0oKLC5pR3kOGTcXLeOY6KjO3rchRG/ePftGcCE/z6fVslUiW9t/5b5Nvel1jWyFongq0vW8Yw0v+CMcxsvHdy7Ei6QXkv4uVga5Qt2yrskx46PFYq830nSSeyR2MZhGcpEG+IMNjEmNjEORMDU1GyTg8aYq5YtIoB0hqiKfyePVwNFoGLuz6PUbaqAZVJCtPBQlGgQ6VK7pO4HKUxeybTnlwWDtpJmPirryF9FdcN3acNdd87F49wSWc5B2U6j62Oqif3Yr7WolF2y3XmKxf67CLeIx1xMmE1qpM1A8ltAAAqHUBoTSI+fzpC3DPQVH/cGlviFrS8stChtHKtJUYZ7f+2EwrTRkLQqwvSlvKRgaqJKCg7vus+we7HbMfBTLipQ9AHQ03nU51tLXnc=
before_install:
- gem install bundler
- bundle --version
before_script:
- echo -e "build ruby version $TRAVIS_RUBY_VERSION"
- if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
- if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi
script: bundle exec rspec
after_script:
- if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
