language: ruby
dist: bionic
rvm:
- 2.6.2
- 2.7
cache:
  bundler: true
notifications:
  slack:
    rooms:
      secure: u/8B1oyLGVu5Ymxl60YfoJDAiqF+ZumKMM+0oMrwuPc3d1xxHNutNGSRVJ2mj6CvVQWFkrAWwFOwpOtq+YxAOR35V32kpso0DcFYhs/3RAK7st5I6dBlXLT0nsh102yRKN7mdAYHolFMSF6szdXJrvEt6aWgWnT5ITHt66ZB6Lt3QRBdybod0MzEdtmYoe12gUBzZqbzA/MIMmy4j49GIazPsiOj7W8g/YV/XW5aozJuu3v6Cp7SRlVclzEDEQQx2oKdXjVArHv9Wc7GVkTrWss5vr8/jny2VQPV+m1gOpn2Ie8x7hlqYEMiz3z1ONQevrs6CgQLJSZ7zj8+73Vye4evxm4MXGrXRZKo4wdXLTJBsOZUWWDpkoJLLNli7uEy03m3ddQW88LkOlG7aRnaoJYIirQmdZ3F5U5+9kyyfbDpUKQswSgxhWH55AHg2jUJhg7fu5aSCUZ10Y6FYXZXdgV1lu4+gWwvo5Hvea54KbjMkzOR4MRiEhz3qZa2r5rsRhyoA3k+kQ+czbUO4gnYmLsK/s6btByI3aICKQgMFzOg5ALM0kytLk/ND7G3uCicco/sWHcV1r5CfEcZgcY+vJnHoz6n96eqLqJfq1ZwDWfsn7DXOUWKuFzOzzdc/EO28yKs31+kZROeP7E3XKm58l7Me1yOkVdr+QeC4mzqhP4=
addons:
  code_climate:
    repo_token:
      secure: "cjZb5/ocz4JV6m0NOow2ljlY5QM2FgL/CigWlo4oV+Vzu02OW3zgwRsv08B3Rd09MEB9V+ETBYFsK3ELitOiQRgeBX0go65j8779vZP97AyDj2QNQhteFsmUJr0HsqI2zLv18Ts2uglWZ4iFwARg9xMK8GMmDm5kx4aWXUFAokIkkTHJJE1cN7v5QOdjrek5CxEOip7hOhOppmKCOOzxsyFow0dwqMBEaIaBS/yFNg8G5rW5RHRUsMdULQziFdmHm1XgJpj5+s4sEcYHQ7a7xehLy2KsZZD5sIYCulGgQawgaPy8JPxxC/K9s9qfR1GZwdujp5tgkQ9eh1LMZKTnXJfIKQj0EwxdTGB3eKA1sgE0xsFyUBQ9EBp0RjORojGFcmNbOiqXBI8EKlwAXBCCTkFI74jl3h4X7prUWiF7WSuk7nwYdoT0zV2GrdqS3BA6O7+FxTFVJiYq6Jl+ECcfmcKfNegSX8kMeHSA2sba9dIEIuXDXFOyPaFGeogHETWJdx2VH1/uEDtVmP6egWl6NGkoJTF/ZWT/TVCUSp+ZHJzIB5ijCFvxx5Ja9VyiDmaUYrcex2o95mVKbq0GYxJDxP1pwe5/4nuOx9s2F9xgzNNorKosE6zP0MuWF0/eULMeM9wR4tIjJFsVpsnGzgEZQ76jB7+kHEeaEIgz7LQddPQ="

before_install:
  - gem install bundler
  - bundle --version

before_script:
  - echo -e "build ruby version $TRAVIS_RUBY_VERSION"
  # Only run code coverage reporting in MRI/YARV
  - if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi

script: bundle exec rspec

after_script:
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
