language: ruby
dist: bionic
rvm:
  - 2.6.2
  - 2.7
cache:
  bundler: true
notifications:
  slack:
    secure: u/8B1oyLGVu5Ymxl60YfoJDAiqF+ZumKMM+0oMrwuPc3d1xxHNutNGSRVJ2mj6CvVQWFkrAWwFOwpOtq+YxAOR35V32kpso0DcFYhs/3RAK7st5I6dBlXLT0nsh102yRKN7mdAYHolFMSF6szdXJrvEt6aWgWnT5ITHt66ZB6Lt3QRBdybod0MzEdtmYoe12gUBzZqbzA/MIMmy4j49GIazPsiOj7W8g/YV/XW5aozJuu3v6Cp7SRlVclzEDEQQx2oKdXjVArHv9Wc7GVkTrWss5vr8/jny2VQPV+m1gOpn2Ie8x7hlqYEMiz3z1ONQevrs6CgQLJSZ7zj8+73Vye4evxm4MXGrXRZKo4wdXLTJBsOZUWWDpkoJLLNli7uEy03m3ddQW88LkOlG7aRnaoJYIirQmdZ3F5U5+9kyyfbDpUKQswSgxhWH55AHg2jUJhg7fu5aSCUZ10Y6FYXZXdgV1lu4+gWwvo5Hvea54KbjMkzOR4MRiEhz3qZa2r5rsRhyoA3k+kQ+czbUO4gnYmLsK/s6btByI3aICKQgMFzOg5ALM0kytLk/ND7G3uCicco/sWHcV1r5CfEcZgcY+vJnHoz6n96eqLqJfq1ZwDWfsn7DXOUWKuFzOzzdc/EO28yKs31+kZROeP7E3XKm58l7Me1yOkVdr+QeC4mzqhP4=
env:
  global:
    - secure: "fe/x9eQf15in6ArIbuwrDPSRyKBBOB0s0XTbYeJOP3QtPNnAVNv+vc3Y21I/9TX3yLBvv2nH/jX+9ih7qmiznZbTOBWjtr42xptbmxJcQNCygLxg039Vn8zbwvGwuKkiToiInwN6bL++NlXhUPlAUnFBbw5olO7PYsQ2dxih+r887CEBFYLY3NijZvdxD157BPyAKNKFOM4e/Ugb10B3LYuU+IzR9qLmPgi7SFthbT6NzqkC20SgPGyIW6JR3BBGiAgfa3tSN7elY4Rqs/pvtqh6Tgvvy5EQMvwbmoMHQJ8NUv0sVyszuOzMWcSWPCByDNGOXMA3efUReDFxQD0tfFsNeQDUGnUAeV8MsYi3K1kCBwEl9wVNJ2kc/ljATtbCYJI75izJsrekPJm3VdXgVECBKurMp4GBke3haEk7sG6ORKwk/CsjqhWcwWBFi2um6OHAfA39WOnmiyi+Oqc0IHToywI1may6J4Xr9QpMbQJmxEoIkmXU0bH6XcND0JRkf8OCq+Af5yOC1h/MHunybbNED+BCx48tIvSrwsZDJjcHnbuU7kwHTkzpLSpynbiTax1mm/OQO+7pFYTQe1o00mx8a04hNvRt5AvLvndc6iqPqvy1PocemDqOPnGjimY68qp+8+YKIJaQZSJDstHN570nn2LIIUtWlASv2rXHZUM="

before_install:
  - gem install bundler
  - bundle --version

before_script:
  - echo -e "build ruby version $TRAVIS_RUBY_VERSION"
  # Only run code coverage reporting in MRI/YARV
  - if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi

script: bundle exec rspec

after_script:
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
